### ISSUE TITLE
希望左下角的剩余时间能设计更好一点

### ISSUE THREAD

**Issue by sky130** [TrueRou/UsagiPass#4]
字体过于突兀

![Screenshot_2024-11-02-09-08-19-417_mark.via.jpg](https://github.com/user-attachments/assets/ef577f2d-0016-4085-bd4a-315858e7d014)

已经用上了，非常不错

**Comment by TrueRou** [comment]
有什么设计建议吗，当前应该是使用的系统默认字体

**Comment by TrueRou** [comment]
改进了字体: 1a692d763bb2d946d6a77c09bbfb9c72f37aeb95
