### ISSUE TITLE
项目需要支持204

### ISSUE THREAD

**Issue by 8MiYile** [TrueRou/UsagiPass#5]
https://wiki.metacubex.one/config/proxy-groups/?h=204
这个是mihomo关于策略组204的使用方法
虽说官网提供的ss节点仅提供302服务 但希望能内置204服务以让第三方程序设置指定的url 以达到检查节点是否工作

**Comment by TrueRou** [comment]
默认的查验域名都是https://www.gstatic.com/generate_204吗，我是不是只要放行https://www.gstatic.com/generate_204走Freedom出口就可以了

**Comment by TrueRou** [comment]
> https://wiki.metacubex.one/config/proxy-groups/?h=204 这个是mihomo关于策略组204的使用方法 虽说官网提供的ss节点仅提供302服务 但希望能内置204服务以让第三方程序设置指定的url 以达到检查节点是否工作

添加了对下面几个常见 204 URL的放行
- http://www.gstatic.com/generate_204
- http://cp.cloudflare.com/generate_204
- http://www.msftconnecttest.com/
- http://captive.apple.com/
